services:
  elasticsearch:
    container_name: gungeonFinder_elastic
    image: elasticsearch:8.14.1
    environment:
      ELASTIC_PASSWORD: "VvVZiNDR7s4nHajE7x90"
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    ports:
      - 9200:9200
    volumes:
      - ./docker/elastic/elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - gungeonFinder-network

  app:
    container_name: gungeonFinder_app
    build: ./src
    depends_on:
      - elasticsearch
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount the X11 socket
    environment:
      DISPLAY: ${DISPLAY}
      ELASTIC_PORT: "9200"
      ELASTIC_HOST: "elasticsearch"
      ELASTIC_PASSWORD: "VvVZiNDR7s4nHajE7x90"
      ELASTIC_USER: "elastic"

    networks:
      - gungeonFinder-network

networks:
  gungeonFinder-network:
    driver: bridge
volumes:
  elastic-data:
    driver: local
