FROM python:3.10-bullseye

RUN apt-get update
RUN apt-get install -y build-essential libgtk-3-dev
RUN pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-11/ wxPython

COPY . /app

WORKDIR /app

RUN python -m pip install --upgrade pip

RUN pip install -e .

CMD ["GungeonFinder"]